spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

logging:
  level:
    com.webservice.be_tailflash: DEBUG
