spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

logging:
  level:
    com.webservice.be_tailflash: DEBUG

app:
  taxonomy:
    dev-auto-create-tags: true
